import Scenes                                                                                                                                                                                                                                  
   2 |                                                                                                                                                                                                                                                
   3 |   /*                                                                                                                                                                                                                                           
   4 |      This class is responsible for the background Layer.                                                                                                                                                                                       
   5 |      Internally, it maintains the RenderableEntities for this layer.                                                                                                                                                                           
   6 |    */                                                                                                                                                                                                                                          
   7 |                                                                                                                                                                                                                                                
   8 |                                                                                                                                                                                                                                                
   9 | class BackgroundLayer : Layer {                                                                                                                                                                                                                
  10 |       let background = Background()                                                                                                                                                                                                            
  11 |                                                                                                                                                                                                                                                
  12 |       init() {                                                                                                                                                                                                                                 
  13 |           // Using a meaningful name can be helpful for debugging                                                                                                                                                                              
  14 |           super.init(name:"Background")                                                                                                                                                                                                        
  15 |                                                                                                                                                                                                                                                
  16 |           // We insert our RenderableEntities in the constructor                                                                                                                                                                               
  17 |           insert(entity:background, at:.back)                                                                                                                                                                                                  
  18 |       }                                                                                                                                                                                                                                        
  19 |   }
