 import Igis                                                                                                                                                                                                                   
   2 | import Scenes                                                                                                                                                                                                                 
   3 |                                                                                                                                                                                                                               
   4 | class Ball: RenderableEntity, MouseMoveHandler {                                                                                                                                                                              
   5 |     var compressedCounter : UInt                                                                                                                                                                                              
   6 |     var velocityX : Int                                                                                                                                                                                                       
   7 |     var velocityY : Int                                                                                                                                                                                                       
   8 |     let text : Text                                                                                                                                                                                                           
   9 |     var didRender = false                                                                                                                                                                                                     
  10 |     let ellipse = Ellipse(center:Point(x:0, y:0), radiusX:20, radiusY:20, fillMode:.fillAndStroke)                                                                                                                            
  11 |     let strokeStyle = StrokeStyle(color:Color(.white))                                                                                                                                                                        
  12 |     let fillStyle = FillStyle(color:Color(.white))                                                                                                                                                                            
  13 |     let lineWidth = LineWidth(width:5)                                                                                                                                                                                        
  14 |     init() {                                                                                                                                                                                                                  
  15 |         velocityX = 0                                                                                                                                                                                                         
  16 |         velocityY = 0                                                                                                                                                                                                         
  17 |         compressedCounter = 0                                                                                                                                                                                                 
  18 |         // Using a meaningful name can be helpful for debugging                                                                                                                                                               
  19 |         text = Text(location:Point(x:520, y:270), text:"Rec Center")                                                                                                                                                          
  20 |         text.font = "15pt Arial"                                                                                                                                                                                              
  21 |         super.init(name:"Ball")                                                                                                                                                                                               
  22 |     }                                                                                                                                                                                                                         
  23 |     func changeVelocity(velocityX:Int, velocityY:Int) {                                                                                                                                                                       
  24 |         self.velocityX = velocityX                                                                                                                                                                                            
  25 |         self.velocityY = velocityY                                                                                                                                                                                            
  26 |     }                                                                                                                                                                                                                         
  27 |     func onMouseMove(globalLocation: Point, movement:Point) {                                                                                                                                                                 
  28 |         ellipse.center = globalLocation                                                                                                                                                                                       
  29 |     }                                                                                                                                                                                                                         
  30 |     override func calculate(canvasSize: Size) {                                                                                                                                                                               
  31 |         ellipse.center += Point(x: velocityX, y: velocityY)                                                                                                                                                                   
  32 |                                                                                                                                                                                                                               
  33 |         // Form a bounding rectangle around the canvas                                                                                                                                                                        
  34 |         let canvasBoundingRect = Rect(size:canvasSize)                                                                                                                                                                        
  35 |                                                                                                                                                                                                                               
  36 |         // Form a bounding rect around the ball (ellipse)                                                                                                                                                                     
  37 |         let ballBoundingRect = Rect(topLeft:Point(x:ellipse.center.x-ellipse.radiusX, y:ellipse.center.y-ellipse.radiusY),                                                                                                    
  38 |                                     size:Size(width:ellipse.radiusX*2, height:ellipse.radiusY*2))                                                                                                                             
  39 |                                                                                                                                                                                                                               
  40 |         // Determine if we've moved outside of the canvas boundary rect                                                                                                                                                       
  41 |         let tooFarLeft = ballBoundingRect.topLeft.x < canvasBoundingRect.topLeft.x                                                                                                                                            
  42 |         let tooFarRight = ballBoundingRect.topLeft.x + ballBoundingRect.size.width > canvasBoundingRect.topLeft.x + canvasBoundingRect.size.width                                                                             
  43 |                                                                                                                                                                                                                               
  44 |         let tooFarUp = ballBoundingRect.topLeft.y < canvasBoundingRect.topLeft.y                                                                                                                                              
  45 |         let tooFarDown = ballBoundingRect.topLeft.y + ballBoundingRect.size.height > canvasBoundingRect.topLeft.y + canvasBoundingRect.size.height                                                                            
  46 |                                                                                                                                                                                                                               
  47 |         if tooFarLeft || tooFarRight {                                                                                                                                                                                        
  48 |             velocityX = -velocityX - 2                                                                                                                                                                                        
  49 |                                                                                                                                                                                                                               
  50 |             ellipse.radiusX = 15                                                                                                                                                                                              
  51 |             ellipse.radiusY = 15
                 compressedCounter = 10                                                                                                                                                                                            
               }                                                                                                                                                                                                                     
               if tooFarUp || tooFarDown {                                                                                                                                                                                           
                   velocityY = -velocityY - 2                                                                                                                                                                                        
                   ellipse.radiusX = 10                                                                                                                                                                                              
                   ellipse.radiusY = 10                                                                                                                                                                                              
                   compressedCounter = 10                                                                                                                                                                                            
               }                                                                                                                                                                                                                     
               if compressedCounter == 0 {                                                                                                                                                                                           
                   ellipse.radiusX = 20                                                                                                                                                                                              
                   ellipse.radiusY = 20                                                                                                                                                                                              
               }else{                                                                                                                                                                                                                
                   compressedCounter -= 1                                                                                                                                                                                            
               }                                                                                                                                                                                                                     
           }                                                                                                                                                                                                                         
               override func setup(canvasSize: Size, canvas: Canvas) {                                                                                                                                                               
                   ellipse.center = canvasSize.center                                                                                                                                                                                
                   dispatcher.registerMouseMoveHandler(handler:self)                                                                                                                                                                 
               }                                                                                                                                                                                                                     
               override func teardown() {                                                                                                                                                                                            
                   dispatcher.unregisterMouseMoveHandler(handler:self)                                                                                                                                                               
               }                                                                                                                                                                                                                     
               override func boundingRect() -> Rect {                                                                                                                                                                                
                   let topLeft = ellipse.center - Point(x: ellipse.radiusX, y: ellipse.radiusY)                                                                                                                                      
                   let size = Size(width: 2 * ellipse.radiusX, height: 2 * ellipse.radiusY)                                                                                                                                          
                   return Rect (topLeft: topLeft, size: size)
                         }                                                                                                                                                                                                                     
               override func render(canvas:Canvas) {                                                                                                                                                                                 
                   let clear = canvas.canvasSize!                                                                                                                                                                                    
                   if let canvasSize = canvas.canvasSize, !didRender {                                                                                                                                                               
                       let clearRect = Rect(topLeft:Point(x:0, y:0), size:canvasSize)                                                                                                                                                
                       let clear  = Rectangle(rect:clearRect, fillMode:.clear)                                                                                                                                                       
                       canvas.render(strokeStyle, lineWidth, fillStyle, ellipse)                                                                                                                                                     
                   }                                                                                                                                                                                                                 
               }                                                                                                                                                                                                                     
           }
