import Igis                                                                                                                                                                                                                   
   2 | import Scenes                                                                                                                                                                                                                 
   3 |                                                                                                                                                                                                                               
   4 | /*                                                                                                                                                                                                                            
   5 |  This class is responsible for the interaction Layer.                                                                                                                                                                         
   6 |  Internally, it maintains the RenderableEntities for this layer.                                                                                                                                                              
   7 |  */                                                                                                                                                                                                                           
   8 |                                                                                                                                                                                                                               
   9 |                                                                                                                                                                                                                               
  10 | class InteractionLayer : Layer, KeyDownHandler {                                                                                                                                                                              
  11 |     static let ball = Ball()                                                                                                                                                                                                  
  12 |     var canvasSize = Size(width: 0, height: 0)                                                                                                                                                                                
  13 |     static let paddleLeft = Paddle(rect:Rect(size:Size(width:20, height:150)))                                                                                                                                                
  14 |     static let paddleRight = Paddle(rect:Rect(size:Size(width:20, height:150)))                                                                                                                                               
  15 |     static let paddletop = Paddle(rect:Rect(size:Size(width:250, height:20)))                                                                                                                                                 
  16 |     static let paddlebottom = Paddle(rect:Rect(size:Size(width:250, height:20)))                                                                                                                                              
  17 |     static let leftScoreboard = Scoreboard()                                                                                                                                                                                  
  18 |     static let rightScoreboard = Scoreboard()                                                                                                                                                                                 
  19 |     static let topScoreboard = Scoreboard()                                                                                                                                                                                   
  20 |     static let bottomScoreboard = Scoreboard()                                                                                                                                                                                
  21 |                                                                                                                                                                                                                               
  22 |     required  init() {                                                                                                                                                                                                        
  23 |         Self.ball.changeVelocity(velocityX: 12, velocityY: 14)                                                                                                                                                                
  24 |         // Using a meaningful name can be helpful for debugging                                                                                                                                                               
  25 |         super.init(name:"Interaction")                                                                                                                                                                                        
  26 |                                                                                                                                                                                                                               
  27 |         // We insert our RenderableEntities in the constructor                                                                                                                                                                
  28 |         insert(entity: Self.ball, at: .front)                                                                                                                                                                                 
  29 |         insert(entity: Self.paddleLeft, at: .front)                                                                                                                                                                           
  30 |         insert(entity: Self.paddleRight, at: .front)                                                                                                                                                                          
  31 |         insert(entity: Self.paddletop, at: .front)                                                                                                                                                                            
  32 |         insert(entity: Self.paddlebottom, at: .front)                                                                                                                                                                         
  33 |         insert(entity: Self.leftScoreboard, at: .front)                                                                                                                                                                       
  34 |         insert(entity: Self.rightScoreboard, at: .front)                                                                                                                                                                      
  35 |         insert(entity: Self.topScoreboard, at: .front)                                                                                                                                                                        
  36 |         insert(entity: Self.bottomScoreboard, at: .front)                                                                                                                                                                     
  37 |     }                                                                                                                                                                                                                         
  38 |     func onKeyDown(key:String, code:String, ctrlKey:Bool, shiftKey:Bool, altKey:Bool, metaKey:Bool) {                                                                                                                         
  39 |         let movement = 70                                                                                                                                                                                                     
  40 |         switch(key) {                                                                                                                                                                                                         
  41 |         case "w" :                                                                                                                                                                                                            
  42 |             //left paddle up                                                                                                                                                                                                  
  43 |             if Self.paddleLeft.rectangle.rect.topLeft.y >= 50 {                                                                                                                                                               
  44 |                 Self.paddleLeft.move(to:Point(x: Self.paddleLeft.rectangle.rect.topLeft.x, y: Self.paddleLeft.rectangle.rect.topLeft.y - movement))                                                                           
  45 |             }                                                                                                                                                                                                                 
  46 |         case "s" :                                                                                                                                                                                                            
  47 |             //left paddle down                                                                                                                                                                                                
  48 |             if Self.paddleLeft.rectangle.rect.topLeft.y <= 790 {                                                                                                                                                              
  49 |                 Self.paddleLeft.move(to:Point(x: Self.paddleLeft.rectangle.rect.topLeft.x, y: Self.paddleLeft.rectangle.rect.topLeft.y + movement))                                                                           
  50 |             }                                                                                                                                                                                                                 
  51 |         case "ArrowUp" :
    //right paddle up                                                                                                                                                                                                                                                                                     
  53 |             if Self.paddleRight.rectangle.rect.topLeft.y >= 50 {                                                                                                                                                                                                                                                  
  54 |                 Self.paddleRight.move(to:Point(x: Self.paddleRight.rectangle.rect.topLeft.x, y: Self.paddleRight.rectangle.rect.topLeft.y - movement))                                                                                                                                                            
  55 |             }                                                                                                                                                                                                                                                                                                     
  56 |         case "ArrowDown" :                                                                                                                                                                                                                                                                                        
  57 |             //right paddle down                                                                                                                                                                                                                                                                                   
  58 |             if Self.paddleRight.rectangle.rect.topLeft.y <= 790 {                                                                                                                                                                                                                                                 
  59 |                 Self.paddleRight.move(to:Point(x: Self.paddleRight.rectangle.rect.topLeft.x, y: Self.paddleRight.rectangle.rect.topLeft.y + movement))                                                                                                                                                            
  60 |             }                                                                                                                                                                                                                                                                                                     
  61 |         case "a" :                                                                                                                                                                                                                                                                                                
  62 |             //top paddleleft                                                                                                                                                                                                                                                                                      
  63 |             if Self.paddletop.rectangle.rect.topLeft.x >= 10 {                                                                                                                                                                                                                                                    
  64 |                 Self.paddletop.move(to:Point(x: Self.paddletop.rectangle.rect.topLeft.x - movement, y: Self.paddletop.rectangle.rect.topLeft.y))                                                                                                                                                                  
  65 |             }                                                                                                                                                                                                                                                                                                     
  66 |         case "d" :                                                                                                                                                                                                                                                                                                
  67 |             //top paddle right                                                                                                                                                                                                                                                                                    
  68 |             if Self.paddletop.rectangle.rect.topLeft.x <= 1580 {                                                                                                                                                                                                                                                  
  69 |                 Self.paddletop.move(to:Point(x: Self.paddletop.rectangle.rect.topLeft.x + movement, y: Self.paddletop.rectangle.rect.topLeft.y))                                                                                                                                                                  
  70 |             }                                                                                                                                                                                                                                                                                                     
  71 |         case "ArrowLeft" :                                                                                                                                                                                                                                                                                        
  72 |             //bottom paddle left                                                                                                                                                                                                                                                                                  
  73 |             if Self.paddlebottom.rectangle.rect.topLeft.y >= 50 {                                                                                                                                                                                                                                                 
  74 |                 Self.paddlebottom.move(to:Point(x: Self.paddlebottom.rectangle.rect.topLeft.x - movement, y: Self.paddlebottom.rectangle.rect.topLeft.y))                                                                                                                                                         
  75 |             }                                                                                                                                                                                                                                                                                                     
  76 |         case "ArrowRight" :                                                                                                                                                                                                                                                                                       
  77 |             //bottom paddle right                                                                                                                                                                                                                                                                                 
  78 |             if Self.paddlebottom.rectangle.rect.topLeft.y <= 1580 {                                                                                                                                                                                                                                               
  79 |                 Self.paddlebottom.move(to:Point(x: Self.paddlebottom.rectangle.rect.topLeft.x + movement, y: Self.paddlebottom.rectangle.rect.topLeft.y))
                }                                                                                                                                                                                                                                                                                                     
               default:                                                                                                                                                                                                                                                                                                  
                   fatalError("needs to work \(key)")                                                                                                                                                                                                                                                                    
               }                                                                                                                                                                                                                                                                                                         
           }                                                                                                                                                                                                                                                                                                             
           override func preSetup(canvasSize: Size, canvas: Canvas) {                                                                                                                                                                                                                                                    
               Self.paddleLeft.move(to:Point(x: 10, y: canvasSize.center.y))                                                                                                                                                                                                                                             
               Self.paddleRight.move(to:Point(x:canvasSize.width-20, y:canvasSize.center.y))                                                                                                                                                                                                                             
               Self.paddletop.move(to:Point(x:canvasSize.center.x, y: 10))                                                                                                                                                                                                                                               
               Self.paddlebottom.move(to:Point(x:canvasSize.center.x, y:canvasSize.height-40))                                                                                                                                                                                                                           
               Self.leftScoreboard.scoreboard.location = Point(x:canvasSize.width/4, y:canvasSize.height/2)                                                                                                                                                                                                              
               Self.rightScoreboard.scoreboard.location = Point(x:3*canvasSize.width/4, y:canvasSize.height/2)                                                                                                                                                                                                           
               Self.topScoreboard.scoreboard.location = Point(x:canvasSize.width/2, y:canvasSize.height/8)                                                                                                                                                                                                               
               Self.bottomScoreboard.scoreboard.location = Point(x:canvasSize.width/2, y:5*canvasSize.height/6)                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                         
               dispatcher.registerKeyDownHandler(handler: self)                                                                                                                                                                                                                                                          
           }                                                                                                                                                                                                                                                                                                             
           override func postTeardown() {                                                                                                                                                                                                                                                                                
               dispatcher.unregisterKeyDownHandler(handler: self)                                                                                                                                                                                                                                                        
           }                                                                                                                                                                                                                                                                                                             
           override func preCalculate(canvas: Canvas) {                                                                                                                                                                                                                                                                  
               let ballCoundingRect = Self.ball.boundingRect()                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                                                         
               let leftPaddleBoundingRect = Self.paddleLeft.boundingRect()                                                                                                                                                                                                                                               
               let leftPaddleContainment = leftPaddleBoundingRect.containment(target: ballCoundingRect)                                                                                                                                                                                                                  
               let leftPaddleTargetContainmentSet: ContainmentSet = [.overlapsRight, .contact]                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                                                         
               if leftPaddleTargetContainmentSet.isSubset(of: leftPaddleContainment){                                                                                                                                                                                                                                    
                   Self.ball.velocityX = -Self.ball.velocityX                                                                                                                                                                                                                                                            
               }                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                         
               let rightPaddleBoundingRect = Self.paddleRight.boundingRect()                                                                                                                                                                                                                                             
               let rightPaddleContainment = rightPaddleBoundingRect.containment(target: ballCoundingRect)                                                                                                                                                                                                                
               let rightPaddleTargetContainmentSet: ContainmentSet = [.overlapsLeft, .contact]                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                                                         
               if rightPaddleTargetContainmentSet.isSubset(of: rightPaddleContainment){                                                                                                                                                                                                                                  
                   Self.ball.velocityX = -Self.ball.velocityX                                                                                                                                                                                                                                                            
               }                                                                                                                                                                                                                                                                                                         
               let topPaddleBoundingRect = Self.paddletop.boundingRect()                                                                                                                                                                                                                                                 
               let topPaddleContainment = topPaddleBoundingRect.containment(target: ballCoundingRect)
             let topPaddleTargetContainmentSet: ContainmentSet = [.overlapsBottom, .contact]                                                                                                                                                                                                                           
 121 |                                                                                                                                                                                                                                                                                                                   
 122 |         if topPaddleTargetContainmentSet.isSubset(of: topPaddleContainment){                                                                                                                                                                                                                                      
 123 |             Self.ball.velocityY = -Self.ball.velocityY                                                                                                                                                                                                                                                            
 124 |         }                                                                                                                                                                                                                                                                                                         
 125 |         let bottomPaddleBoundingRect = Self.paddlebottom.boundingRect()                                                                                                                                                                                                                                           
 126 |         let bottomPaddleContainment = bottomPaddleBoundingRect.containment(target: ballCoundingRect)                                                                                                                                                                                                              
 127 |         let bottomPaddleTargetContainmentSet: ContainmentSet = [.overlapsTop, .contact]                                                                                                                                                                                                                           
 128 |                                                                                                                                                                                                                                                                                                                   
 129 |         if bottomPaddleTargetContainmentSet.isSubset(of: bottomPaddleContainment){                                                                                                                                                                                                                                
 130 |             Self.ball.velocityY = -Self.ball.velocityY                                                                                                                                                                                                                                                            
 131 |         }                                                                                                                                                                                                                                                                                                         
 132 |     }                                                                                                                                                                                                                                                                                                             
 133 |                                                                                                                                                                                                                                                                                                                   
 134 |     override func postCalculate(canvas:Canvas){ //1899                                                                                                                                                                                                                                                            
 135 |         if Self.ball.boundingRect().topRight.x >= 1899 {                                                                                                                                                                                                                                                          
 136 |             Self.leftScoreboard.addScore(amount: 1)                                                                                                                                                                                                                                                               
 137 |         }                                                                                                                                                                                                                                                                                                         
 138 |         if Self.ball.boundingRect().topLeft.x <= 2/4 {                                                                                                                                                                                                                                                            
 139 |             Self.rightScoreboard.addScore(amount: 1)                                                                                                                                                                                                                                                              
 140 |         }                                                                                                                                                                                                                                                                                                         
 141 |         if Self.ball.boundingRect().topLeft.y <= 1 {                                                                                                                                                                                                                                                              
 142 |             Self.topScoreboard.addScore(amount: 1)                                                                                                                                                                                                                                                                
 143 |         }                                                                                                                                                                                                                                                                                                         
 144 |         if Self.ball.boundingRect().topLeft.y >= 915 {                                                                                                                                                                                                                                                            
 145 |             Self.bottomScoreboard.addScore(amount: 1)                                                                                                                                                                                                                                                             
 146 |         }                                                                                                                                                                                                                                                                                                         
 147 |     }                                                                                                                                                                                                                                                                                                             
 148 |                                                                                                                                                                                                                                                                                                                   
 149 | }
