import Igis                                                                                                                                                                                                                                    
   2 |                                                                                                                                                                                                                       no such module 'Igis'    
   3 | /*                                                                                                                                                                                                                                             
   4 |  This main code is responsible for starting Igis and initializing                                                                                                                                                                              
   5 |  the Director.                                                                                                                                                                                                                                 
   6 |  It rarely needs to be altered.                                                                                                                                                                                                                
   7 |  */                                                                                                                                                                                                                                            
   8 | print("Starting...")                                                                                                                                                                                                                           
   9 | do {                                                                                                                                                                                                                                           
  10 |     let igis = Igis()                                                                                                                                                                                                                          
  11 |     try igis.run(painterType:ShellDirector.self)                                                                                                                                                                                               
  12 | } catch (let error) {                                                                                                                                                                                                                          
  13 |     print("Error: \(error)")                                                                                                                                                                                                                   
  14 | }                                                                                                                                                                                                                                              
  15 | 
