import Scenes                                                                                                                                                                                                                                  
   2 |                                                                                                                                                                                                                                                
   3 | /*                                                                                                                                                                                                                                             
   4 |    This class is responsible for implementing a single Scene.                                                                                                                                                                                  
   5 |    Scenes projects require at least one Scene but may have many.                                                                                                                                                                               
   6 |    A Scene is comprised of one or more Layers.                                                                                                                                                                                                 
   7 |    Layers are generally added in the constructor.                                                                                                                                                                                              
   8 |  */                                                                                                                                                                                                                                            
   9 | class MainScene : Scene {                                                                                                                                                                                                                      
  10 |                                                                                                                                                                                                                                                
  11 |     /* Scenes typically include one or more Layers.                                                                                                                                                                                            
  12 |        A common approach is to use three Layers:                                                                                                                                                                                               
  13 |        One for the background, one for interaction,                                                                                                                                                                                            
  14 |        and one for the foreground.                                                                                                                                                                                                             
  15 |      */                                                                                                                                                                                                                                        
  16 |     let backgroundLayer = BackgroundLayer()                                                                                                                                                                                                    
  17 |     let interactionLayer = InteractionLayer()                                                                                                                                                                                                  
  18 |     let foregroundLayer = ForegroundLayer()                                                                                                                                                                                                    
  19 |                                                                                                                                                                                                                                                
  20 |     init() {                                                                                                                                                                                                                                   
  21 |         // Using a meaningful name can be helpful for debugging                                                                                                                                                                                
  22 |         super.init(name:"Main")                                                                                                                                                                                                                
  23 |                                                                                                                                                                                                                                                
  24 |         // We insert our Layers in the constructor                                                                                                                                                                                             
  25 |         // We place each layer in front of the previous layer                                                                                                                                                                                  
  26 |         insert(layer:backgroundLayer, at:.back)                                                                                                                                                                                                
  27 |         insert(layer:interactionLayer, at:.inFrontOf(object:backgroundLayer))                                                                                                                                                                  
  28 |         insert(layer:foregroundLayer, at:.front)                                                                                                                                                                                               
  29 |     }                                                                                                                                                                                                                                          
  30 | }
