 import Igis                                                                                                                                                                                                                                                                                                       
   2 | import Scenes                                                                                                                                                                                                                                                                                                     
   3 |                                                                                                                                                                                                                                                                                                                   
   4 | class Paddle: RenderableEntity {                                                                                                                                                                                                                                                                                  
   5 |     var rectangle: Rectangle                                                                                                                                                                                                                                                                                      
   6 |                                                                                                                                                                                                                                                                                                                   
   7 |     init(rect:Rect) {                                                                                                                                                                                                                                                                                             
   8 |         rectangle = Rectangle(rect:rect, fillMode:.fillAndStroke)                                                                                                                                                                                                                                                 
   9 |         // Using a meaningful name can be helpful for debugging                                                                                                                                                                                                                                                   
  10 |         super.init(name: "Paddle")                                                                                                                                                                                                                                                                                
  11 |     }                                                                                                                                                                                                                                                                                                             
  12 |                                                                                                                                                                                                                                                                                                                   
  13 |     override func render(canvas:Canvas) {                                                                                                                                                                                                                                                                         
  14 |         let strokeStyle = StrokeStyle(color:Color(.black))                                                                                                                                                                                                                                                        
  15 |         let fillStyle = FillStyle(color:Color(.white))                                                                                                                                                                                                                                                            
  16 |         let lineWidth = LineWidth(width:2)                                                                                                                                                                                                                                                                        
  17 |         canvas.render(strokeStyle, fillStyle, lineWidth, rectangle)                                                                                                                                                                                                                                               
  18 |     }                                                                                                                                                                                                                                                                                                             
  19 |                                                                                                                                                                                                                                                                                                                   
  20 |     func move(to point:Point) {                                                                                                                                                                                                                                                                                   
  21 |         rectangle.rect.topLeft = point                                                                                                                                                                                                                                                                            
  22 |     }                                                                                                                                                                                                                                                                                                             
  23 |     override func boundingRect() -> Rect {                                                                                                                                                                                                                                                                        
  24 |         return rectangle.rect                                                                                                                                                                                                                                                                                     
  25 |     }                                                                                                                                                                                                                                                                                                             
  26 |     override func calculate(canvasSize: Size) {                                                                                                                                                                                                                                                                   
  27 |         let canvasBoundingRect = Rect(size:canvasSize)                                                                                                                                                                                                                                                            
  28 |         let paddleBoundingRect = Rect(topLeft:Point(x:rectangle.rect.center.x, y: rectangle.rect.center.y),                                                                                                                                                                                                       
  29 |                                       size:Size(width:rectangle.rect.width, height: rectangle.rect.height))                                                                                                                                                                                                       
  30 |                                                                                                                                                                                                                                                                                                                   
  31 |                                                                                                                                                                                                                                                                                                                   
  32 |     }                                                                                                                                                                                                                                                                                                             
  33 | }                                                                                                                                                                                                                                                                                                                 
        
